/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        "inverse-primary": "var(--color-inverse-primary)",
        "on-primary-fixed-variant": "var(--color-on-primary-fixed-variant)",
        "surface-tint": "var(--color-surface-tint)",
        "on-tertiary": "var(--color-on-tertiary)",
        "on-secondary-fixed-variant": "var(--color-on-secondary-fixed-variant)",
        "on-primary": "var(--color-on-primary)",
        "secondary-container": "var(--color-secondary-container)",
        "on-surface": "var(--color-on-surface)",
        "on-surface-variant": "var(--color-on-surface-variant)",
        "primary-fixed": "var(--color-primary-fixed)",
        "inverse-on-surface": "var(--color-inverse-on-surface)",
        "secondary-fixed": "var(--color-secondary-fixed)",
        "inverse-surface": "var(--color-inverse-surface)",
        "surface-container-low": "var(--color-surface-container-low)",
        "on-primary-container": "var(--color-on-primary-container)",
        "background": "var(--color-background)",
        "tertiary-fixed": "var(--color-tertiary-fixed)",
        "on-primary-fixed": "var(--color-on-primary-fixed)",
        "on-secondary": "var(--color-on-secondary)",
        "on-secondary-fixed": "var(--color-on-secondary-fixed)",
        "primary-fixed-dim": "var(--color-primary-fixed-dim)",
        "on-tertiary-container": "var(--color-on-tertiary-container)",
        "tertiary": "var(--color-tertiary)",
        "surface-bright": "var(--color-surface-bright)",
        "secondary-fixed-dim": "var(--color-secondary-fixed-dim)",
        "primary": "var(--color-primary)",
        "outline": "var(--color-outline)",
        "surface-container-lowest": "var(--color-surface-container-lowest)",
        "primary-container": "var(--color-primary-container)",
        "surface-container": "var(--color-surface-container)",
        "on-background": "var(--color-on-background)",
        "surface-variant": "var(--color-surface-variant)",
        "tertiary-fixed-dim": "var(--color-tertiary-fixed-dim)",
        "secondary": "var(--color-secondary)",
        "surface-container-high": "var(--color-surface-container-high)",
        "surface-dim": "var(--color-surface-dim)",
        "on-error-container": "var(--color-on-error-container)",
        "error-container": "var(--color-error-container)",
        "on-error": "var(--color-on-error)",
        "on-tertiary-fixed-variant": "var(--color-on-tertiary-fixed-variant)",
        "surface-container-highest": "var(--color-surface-container-highest)",
        "surface": "var(--color-surface)",
        "outline-variant": "var(--color-outline-variant)",
        "error": "var(--color-error)",
        "on-tertiary-fixed": "var(--color-on-tertiary-fixed)",
        "on-secondary-container": "var(--color-on-secondary-container)",
        "tertiary-container": "var(--color-tertiary-container)"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "max_width": "1600px",
        "lg": "32px",
        "xs": "8px",
        "md": "24px",
        "xl": "48px",
        "base": "4px",
        "gutter": "24px",
        "margin": "32px",
        "sm": "16px"
      }
    },
  },
  plugins: [],
}
