/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        "inverse-primary": "#515f78",
        "on-primary-fixed-variant": "#39475f",
        "surface-tint": "#b9c7e4",
        "on-tertiary": "#00390a",
        "on-secondary-fixed-variant": "#004f54",
        "on-primary": "#233148",
        "secondary-container": "#00f1fe",
        "on-surface": "#e0e3e6",
        "on-surface-variant": "#c5c6cd",
        "primary-fixed": "#d6e3ff",
        "inverse-on-surface": "#2d3133",
        "secondary-fixed": "#74f5ff",
        "inverse-surface": "#e0e3e6",
        "surface-container-low": "#191c1e",
        "on-primary-container": "#74829d",
        "background": "#101416",
        "tertiary-fixed": "#94f990",
        "on-primary-fixed": "#0d1c32",
        "on-secondary": "#00363a",
        "on-secondary-fixed": "#002022",
        "primary-fixed-dim": "#b9c7e4",
        "on-tertiary-container": "#309539",
        "tertiary": "#78dc77",
        "surface-bright": "#363a3c",
        "secondary-fixed-dim": "#00dbe7",
        "primary": "#b9c7e4",
        "outline": "#8f9097",
        "surface-container-lowest": "#0b0f11",
        "primary-container": "#0a192f",
        "surface-container": "#1d2022",
        "on-background": "#e0e3e6",
        "surface-variant": "#323538",
        "tertiary-fixed-dim": "#78dc77",
        "secondary": "#ddfcff",
        "surface-container-high": "#272a2d",
        "surface-dim": "#101416",
        "on-error-container": "#ffdad6",
        "error-container": "#93000a",
        "on-error": "#690005",
        "on-tertiary-fixed-variant": "#005313",
        "surface-container-highest": "#323538",
        "surface": "#101416",
        "outline-variant": "#44474d",
        "error": "#ffb4ab",
        "on-tertiary-fixed": "#002204",
        "on-secondary-container": "#006a70",
        "tertiary-container": "#001f03"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "max_width": "1600px",
        "lg": "32px",
        "xs": "8px",
        "md": "24px",
        "xl": "48px",
        "base": "4px",
        "gutter": "24px",
        "margin": "32px",
        "sm": "16px"
      }
    },
  },
  plugins: [],
}
